language: python

sudo: false

matrix:
  include:
    - env: TOXENV="pep8 py36"
      python: 3.6
      dist: xenial
      sudo: true

install: 
  - pip install -U setuptools
  - pip install -r tests/requirements.txt
  - python setup.py develop

script:
  - tox
